#!/bin/bash 
# description: haproxy load balancer 
# chkconfig:2345 85 15 

#DAEMON=/usr/local/haproxy/sbin/haproxy 
DAEMON=haproxy 
PROG_DIR=/usr/local/haproxy 
RETVAL=0 

start() 
{
HASTAT=$(netstat -tnlp |grep $DAEMON) 
if [ -z "$HASTAT" ]; then
        echo -en "starting $DAEMON ......\t\t\t"
        $DAEMON -f ${PROG_DIR}/conf/${DAEMON}.cfg>/dev/null
        echo -e "\e[32;1m[OK]\e[0m"
else 
        echo "$DAEMON alread running."
        RETVAL=1 
fi
}

stop()
{
HASTAT=$(netstat -tnlp |grep $DAEMON) 
if [ -n "$HASTAT" ]; then
        echo -en "stopping $DAEMON ......\t\t\t"
        kill $(cat ${PROG_DIR}/run/${DAEMON}.pid) >/dev/null
        echo -e "\e[32;1m[OK]\e[0m"
else 
        echo "$DAEMON already stopped."
        RETVAL=2
fi
}

restart()
{
echo -en "restrting $DAEMON ......\t\t\t"
$DAEMON -f ${PROG_DIR}/conf/${DAEMON}.cfg -st $(cat ${PROG_DIR}/run/${DAEMON}.pid) >/dev/null
echo -e "\e[32;1m[OK]\e[0m"
}

status()
{
HASTAT=$(netstat -tnlp|grep $DAEMON)
if [ -z "$HASTAT" ]; then
echo "$DAEMON stopped."
else
echo "$DAEMON running"
fi
}

case "$1" in 
start) 
start 
;;
stop) 
stop 
;;
restart) 
restart
;;
status) 
status
;;
*)
echo "Usage: /etc/init.d/$DAEMON {start|stop|restart|status}"
RETVAL=3 
esac 

exit $RETVAL
