#!/usr/bin/env expect
# ./expect5 $1 $2 $3
#远程登录主机并创建用户 
set ip [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set timeout 10
spawn ssh $user@$ip
expect {
"yes/no" { send "yes\n";exp_continue }
"password" { send "$password\n" }
}
expect "]#" { send "useradd user1\n" }
expect "]#" { send "echo magedu |passwd --stdin user1\n" }
send "exit\n"
expect eof
